version: '3.8'

services:
  web:
    build: .
    command: gunicorn lib_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=myprojectdb
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=mypassword